version: "3.9"

services:
  observability:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME: "aptiview_observability"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - postgres
      - redis

  observability-worker:
    build: .
    command: sh -c "python manage.py migrate && python manage.py run_checks"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME: "aptiview_observability"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "aptiview_observability"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
