# Generated by Django 5.2.13 on 2026-04-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='consecutive_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('outage', 'Outage'), ('recovery', 'Recovery')], max_length=20),
        ),
    ]
