# Generated by Django 5.2.13 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0002_servicestatus_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('outage', 'Outage')], max_length=20),
        ),
    ]
