# Generated by Django 5.2.13 on 2026-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0003_alter_servicestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='criticality',
            field=models.CharField(choices=[('critical', 'Critical'), ('non_critical', 'Non-Critical')], default='critical', max_length=20),
        ),
    ]
